In [1]:
import numpy as np

In [7]:
#Question 1
#Arrays
arr = list(map(int, input().split(" ")))
arr.reverse()
n = np.array(arr, dtype=float)
print(n)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


In [10]:
#Question 2
#Shape and Reshape
n = list(map(int, input().split(" ")))
arr = np.array(n)
arr = np.reshape(arr, (3,3))
print(arr)

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
#Question 3
#Transpose and Flatten
n, m = input().split()
n, m = int(n), int(m)
arr = []
for i in range(n):
  a = list(map(int, input().split(" ")))
  arr.append(a)
arr = np.array(arr)
print(arr.T)
print(arr.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


In [13]:
#Question 4
#Concatenate
n, m, p = input().split(" ")
n, m, p = int(n), int(m), int(p)
arr1 = []
arr2 = []
for i in range(n):
  d = list(map(int, input().split(" ")))
  arr1.append(d)
for i in range(m):
  d = list(map(int, input().split(" ")))
  arr2.append(d)
arr1 = np.array(arr1)
arr2 = np.array(arr2)
print(np.concatenate((arr1, arr2), axis = 0))

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


In [15]:
#Question 5
#Zeros and Ones
shape = tuple(map(int, input().split(" ")))
print(np.zeros(shape, dtype=int))
print(np.ones(shape, dtype=int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [17]:
#Question 6
#Eye and Identity
np.set_printoptions(legacy="1.13")
n, m = input().split(" ")
n, m = int(n), int(m)
print(np.eye(n, m, k = 0))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [24]:
#Question 7
#Array Mathematics
n, m = input().split(" ")
n, m = int(n), int(m)
arr1 = []
arr2 = []
for i in range(n):
  d = list(map(int, input().split(" ")))
  arr1.append(d)
for i in range(n):
  d = list(map(int, input().split(" ")))
  arr2.append(d)
arr1 = np.array(arr1)
arr2 = np.array(arr2)
print(np.add(arr1, arr2))
print(np.subtract(arr1, arr2))
print(np.multiply(arr1, arr2))
print(np.floor_divide(arr1, arr2))
print(np.mod(arr1, arr2))
print(np.power(arr1, arr2))

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


In [26]:
#Question 8 
#Floor, Ceil and Rint
np.set_printoptions(legacy="1.13")
arr = list(map(float, input().split(" ")))
arr = np.array(arr)
print(np.floor(arr))
print(np.ceil(arr))
print(np.rint(arr))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


In [30]:
#Question 9
#Sum and Prod
n, m = input().split(" ")
n, m = int(n), int(m)
arr = []
for _ in range(n):
  d = list(map(int, input().split(" ")))
  arr.append(d)
arr = np.array(arr)
print(np.product(np.sum(arr, axis = 0), axis = 0))

2 2
1 2
3 4
24


In [33]:
#Question 10
#Min and Max
n, m = input().split(" ")
n, m = int(n), int(m)
arr = []
for _ in range(n):
  d = list(map(int, input().split(" ")))
  arr.append(d)
arr = np.array(arr)
min = np.min(arr, axis = 1)
print(np.max(min))

4 2
2 5
3 7
1 3
4 0
3


In [35]:
#Question 11
#Mean, Var, and Std
np.set_printoptions(legacy="1.13")
n, m = input().split(" ")
n, m = int(n), int(m)
arr = []
for _ in range(n):
  d = list(map(int, input().split(" ")))
  arr.append(d)
arr = np.array(arr)
print(np.mean(arr, axis = 1))
print(np.var(arr, axis = 0))
print(np.std(arr))

2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


In [37]:
#Question 12
#Dot and Cross
n = int(input())
a = []
b = []
for _ in range(n):
  d = list(map(int, input().split(" ")))
  a.append(d)
for _ in range(n):
  d = list(map(int, input().split(" ")))
  b.append(d)
a = np.array(a)
b = np.array(b)
print(np.dot(a, b))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


In [38]:
#Question 13
#Inner and Outer
a = list(map(int, input().split(" ")))
b = list(map(int, input().split(" ")))
a = np.array(a)
b = np.array(b)
print(np.inner(a, b))
print(np.outer(a, b))

0 1
2 3
3
[[0 0]
 [2 3]]


In [42]:
#Question 14
#Polynomials
arr = list(map(float, input().split(" ")))
n = int(input())
arr = np.array(arr)
print(np.polyval(arr, n))

1.1 2 3
0
3.0


In [45]:
#Question 15
#Linear Algebra
n = int(input())
arr = []
for _ in range(n):
  d = list(map(float, input().split(" ")))
  arr.append(d)
arr = np.array(arr)
print(np.linalg.det(arr).round(2))

2
1.1 1.1
1.1 1.1
0.0
